language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $D_USER -p $D_PASSWORD
  - export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi"
  - export NAME=teens-search-service
  - docker build -t $NAME .
  - docker tag $NAME:$TAG $NAME/$TAG
  - docker push $NAME

notifications
  email:
    recipients:
    - akrotov.direct@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="ed56986c-87ec-4589-9835-99a84c0cb8bf"