language: java
jdk: oraclejdk8
sudo: required

addons:
  ssh_known_hosts:
    - $RS_ADDRESS

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $D_USER -p $D_PASSWORD
 # - export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi"
  - export NAME=teens-search-service
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker build -t $NAME .; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker tag $NAME $DH_USER/$NAME; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push $DH_USER/$NAME; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then chmod 400 $SSH_PATH; fi
  - eval "$(ssh-agent -s)"
  - ssh-add ./travis-ci
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ssh -i $SSH_PATH $RS_USER@$RS_ADDRESS /home/$RS_USER/$DEPLOY_SCRIPT; fi

notifications:
  email:
    recipients:
    - $MY_EMAIL
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="$CODECOV_TOKEN"