language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - akrotov.direct@gmail.com
    on_success: never
    on_failure: always